### ISSUE TITLE
Use `lake check-test` to detect absence of a test runner

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean-action#26]
`lake check-test` will return exit code 1 if no test runner is available.

When lean-action tries to run tests, we should check this first, and provide a helpful error message. (For now, as the test framework is changing quickly, it doesn't need to be particularly helpful! Later we can point to some proper documentation on how to set up test runners.)

**Comment by austinletson** [comment]
We can use [job summaries](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) for the error messages here so users don't have to dig through the workflow logs.

Something like this:
![2024-05-17-16:11:34-screenshot](https://github.com/leanprover/lean-action/assets/21346448/7684104a-3183-4033-bca2-9334a2980a7b)

More generally, we could add job summaries for failures in other steps of `lean-action`. Since they support markdown there are a lot of possibilities (see [this](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) GitHub blog post). Potentially links to the line which caused a failure in `lake build` or `lake test`?

**Comment by oliver-butterley** [comment]
Yes, job summaries would be convenient for the user of the action. [I responded in the PR for no good reason](https://github.com/leanprover/lean-action/pull/31#issuecomment-2119117673).

- Full job summary for the entire job? 
- Fast fail on steps or try to complete as many steps as possible for additional feedback and then fail at the end?

**Comment by austinletson** [comment]
> * Full job summary for the entire job?
> * Fast fail on steps or try to complete as many steps as possible for additional feedback and then fail at the end?

I think these are both worthwhile enhancements. I think the reservoir check is probably the only step which would make sense to run if previous steps failed.
