### ISSUE TITLE
install elan on windows

### ISSUE THREAD

**Issue by Seasawher** [leanprover/lean-action#75]
I have created a workflow running on Windows.

see: https://github.com/lean-ja/lean-by-example/blob/edc6f5e9d023b0f4c4beb26474e1b678b8e9ba5e/.github/workflows/ci.yml#L29

Almost always building on Windows is not necessary, but I sometimes need this. (For example, when trying to provide an environment which reproduce a lean bug on Windows machine...)

**Comment by Seasawher** [comment]
I think there should be a conditional branch that detects the runner OS and installs elan in a different way if it is Windows. How do you think?

**Comment by austinletson** [comment]
It would be possible to use conditional logic to achieve this, however, I think it would require rewriting most of [the scripts that power most of the functionality of lean-action](https://github.com/leanprover/lean-action/tree/main/scripts) for a Windows environment since they are written in Bash.

I know some GitHub actions support multiple runner operating systems by writing the action in TypeScript instead of having shell scripts and then using shell scripts for specific OS-specific components, e.g., [setup-PHP](https://github.com/shivammathur/setup-php/tree/main/src/scripts). There are other advantages to using TypeScript instead of the current `lean-action` architecture so this could be a worthwhile refactor in the future.

**Comment by austinletson** [comment]
Thank you for the tip here @joneugster!

I have a PR open to add support for Windows runners. We can use the existing scripts with a slight modification to the call site because of a known issue with GitHub custom actions ([link to issue](https://github.com/actions/runner/issues/71)).

Windows runner support should be available in the next week or two with the next release of `lean-action`.
